services:
  backend:
    build: ./backend
    env_file: "./backend/.env"
    ports:
      - "8006:8000"
      - "8678:5678"
      - "8679:5679"
      - "6080:6080"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db

